### PR TITLE
Allow regular Docker builds (not only RH Docker variant)

### PR DESCRIPTION
**Pull request by vblagoje**
Add an ability to build an image with a regular/official Docker. datagrid71-dev branch only

### CODE REVIEW

**Review by slaskawi — APPROVED** [review]
I'm OK with this change, however I advice to shoot an email to CE mailing list and ask about general guidance to proceed in such cases. Maybe we should migrate all other repos to "long prefixes" as well?

**Comment by vblagoje** [comment]
Yeah, I see no point in using RH Docker addressing format because changes causing incompatibility with the official Docker are so minimal yet they cause so much headache for us who are using the official Docker version.

**Comment by osnipso** [comment]
I believe there is no need for this change if we do use proper configuration in both `/etc/sysconfig/docker` and `/etc/containers/registries.conf`. @vblagoje, I have sent you (cloud stream/ Environment setup topic on Zulip) links to both files I have taken from a CE development server (mine is a mess, would have to clean it up before sending). Did you happen to do this configuration? Any changes?

**Comment by ryanemerson** [comment]
@vblagoje @osnipso Can we close this?

**Comment by vblagoje** [comment]
Yes @ryanemerson

**Pull request closed without merging**
