### PR TITLE
[CLOUD-2815] Update images to JDG 7.2.2

### PR DESCRIPTION
**Pull request by osnipso**
Link to JIRAs:
* https://issues.jboss.org/browse/JDG-2069
* https://issues.jboss.org/browse/CLOUD-2815

Back to the patch approach, after using full server .zip ([CLOUD-2540](https://issues.jboss.org/browse/CLOUD-2540))
Gets rid of the patch files after applying them, saving on image size

Signed-off-by: Osni Oliveira <osni.oliveira@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for other issues
- [X] Attached commits represent units of work and are properly formatted
- [X] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [X] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by osnipso** [comment]
Please, let's wait until Sprint 22 is released (DG72/Cache Service) before merging this one.

**Review by ryanemerson — COMMENTED** [review]
@osnipso Can you split this work into two commits? One for CLOUD-2540 and one for CLOUD-2815. Or at the very least reference CLOUD-2540 in the commit message so that we can find where the issue was fixed when searching the history.

**Comment by osnipso** [comment]
@ryanemerson initially, I did CLOUD-2815 and remembered about CLOUD-2540 (it was in the backlog, not scheduled for any sprint or release), it came almost as a "collateral effect" (or, better yet, "solved CLOUD-2815 in CLOUD-2540 style").
But, after you mentioned, I figured it's not hard to do separate steps/commits, little additional work and big benefits.
Good catch, will do! :thumbsup: :recycle:

**Comment by osnipso** [comment]
@ryanemerson PTAL, did as we discussed. Cheers!

**Review by ryanemerson — APPROVED** [review]

**Pull request merged**
