### PR TITLE
CLOUD-2306 JDG 7.2.0.ER3 update

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/CLOUD-2306

//cc @ryanemerson @osnipso

### CODE REVIEW

**Comment by ryanemerson** [comment]
@slaskawi LGTM, but I don't have write access so I can't leave an official review/merge.

**Review by osnipso — APPROVED** [review]
LGTM. I'm approving, but I don't have write access either.

**Comment by slaskawi** [comment]
@goldmann Could you please merge it?

**Comment by goldmann** [comment]
I invited Osni so he can merge it too. BTW, @slaskawi - you are the team maintainer, you can manage people who should have access to JDG repos.

**Comment by slaskawi** [comment]
Alright! Thanks Marek!

**Pull request merged**
